2024-02-19 22:09:05,150 INFO    MainThread:765 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 22:09:05,152 INFO    MainThread:765 [wandb_setup.py:_flush():76] Configure stats pid to 765
2024-02-19 22:09:05,153 INFO    MainThread:765 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-02-19 22:09:05,155 INFO    MainThread:765 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Mental-Disorder-Classification/wandb/settings
2024-02-19 22:09:05,156 INFO    MainThread:765 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-19 22:09:05,157 INFO    MainThread:765 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 22:09:05,159 INFO    MainThread:765 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-02-19 22:09:05,161 INFO    MainThread:765 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Mental-Disorder-Classification/wandb/run-20240219_220905-Updated_table/logs/debug.log
2024-02-19 22:09:05,163 INFO    MainThread:765 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Mental-Disorder-Classification/wandb/run-20240219_220905-Updated_table/logs/debug-internal.log
2024-02-19 22:09:05,164 INFO    MainThread:765 [wandb_init.py:init():566] calling init triggers
2024-02-19 22:09:05,165 INFO    MainThread:765 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-19 22:09:05,167 INFO    MainThread:765 [wandb_init.py:init():591] re-initializing run, found existing run on stack: table
2024-02-19 22:09:05,172 INFO    MainThread:765 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Mental-Disorder-Classification/table
2024-02-19 22:09:05,175 ERROR   MainThread:765 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-02-19 22:09:05,177 INFO    MainThread:765 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 22:09:05,178 INFO    MainThread:765 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 22:09:05,180 INFO    MainThread:765 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 22:09:05,183 INFO    MainThread:765 [wandb_run.py:_restore():2193] restore
2024-02-19 22:09:05,184 INFO    MainThread:765 [wandb_run.py:_restore():2199] restore done
2024-02-19 22:09:33,849 INFO    MainThread:765 [wandb_init.py:init():616] starting backend
2024-02-19 22:09:33,850 INFO    MainThread:765 [wandb_init.py:init():620] setting up manager
2024-02-19 22:09:33,859 INFO    MainThread:765 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 22:09:33,860 INFO    MainThread:765 [wandb_init.py:init():628] backend started and connected
2024-02-19 22:09:33,879 INFO    MainThread:765 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 22:09:33,880 INFO    MainThread:765 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 22:09:33,880 INFO    MainThread:765 [wandb_init.py:init():720] updated telemetry
2024-02-19 22:09:34,054 INFO    MainThread:765 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
